---
# tasks file for roles/install_nic
- name: Create Namespace and Service Account
  kubernetes.core.k8s:
    state: "{{ package_state }}"
    definition: "{{ lookup('file', 'files/ns-and-sa.yaml') | from_yaml_all }}"

- name: NGINX JWT in a Docker Config Secret
  ansible.builtin.command: 
    cmd: kubectl create secret docker-registry regcred --docker-server=private-registry.nginx.com --docker-username="{{nginx_jwt}}" --docker-password=none -n nginx-ingress
  ignore_errors: true
  become: true
  #no_log: true

- name: Deploy NGINX NIC Deployment
  kubernetes.core.k8s:
    state: "{{ package_state }}"
    definition: "{{ lookup('file', 'files/{{item}}.yaml') | from_yaml_all }}"  
  with_items: 

    - rbac
    - default-server-secret.yaml
    - nginx-config
    - ingress-class

    - k8s.nginx.org_virtualservers
    - k8s.nginx.org_virtualserverroutes
    - k8s.nginx.org_transportservers
    - k8s.nginx.org_policies
    - k8s.nginx.org_globalconfigurations

    - nginx-plus-ingress
    - nginx-service

- name: NGINX Secrets
  kubernetes.core.k8s:
    state: "{{ package_state }}"
    definition: "{{ lookup('template', 'templates/nginx-server-secret.j2') | from_yaml_all }}"      

- name: Manage Dashboard Deployment
  kubernetes.core.k8s:
    state: "{{ package_state }}"
    definition: "{{ lookup('template', 'templates/nginx-dashboard.j2') | from_yaml_all }}"