---
# defaults file for roles/install_cis
cis_version: 2.20.0
static_routing_mode: true
orchestration_cni: calico-k8s
log_level: WARNING
pool_member_type: cluster
gtm_username: admin
gtm_password: bigip123
gtm_url: 10.1.20.4