---
# tasks file for roles/deploy_cafe
- name: Manage Cafe APP Deployment
  kubernetes.core.k8s:
    namespace: default
    state: "{{ package_state }}"
    definition: "{{ lookup('file', 'files/{{item}}.yaml') | from_yaml_all }}"  
  with_items: 
    - cafe
#    - ap-dataguard-alarm-policy
#    - ap-logconf
#    - ap-apple-uds    

- name: APP Secrets
  kubernetes.core.k8s:
    namespace: default
    state: "{{ package_state }}"
    definition: "{{ lookup('template', 'files/cafe-secret.j2') | from_yaml_all }}" 

- name: Manage Ingresslink and ExternalDNS CRD
  kubernetes.core.k8s:
    namespace: default
    state: "{{ package_state }}"
    definition: "{{ lookup('template', 'files/{{item}}.yaml') | from_yaml_all }}"  
  with_items: 
    - cafe-virtual-server.yaml
    - vs-ingresslink
    - edns-cafe
