- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: '{{ package_state }}'

- name: Cert Manager
  kubernetes.core.k8s:
    state: '{{ package_state }}'
    definition: "{{ lookup('template', 'templates/cert_manager.j2') | from_yaml_all }}"
    validate:
      fail_on_error: yes 

- name: Create or update the TLS secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: /home/{{admin_account}}/.kube/config
    definition: "{{ lookup('template', 'templates/tls.secret.j2') | from_yaml_all }}"
    validate:
      fail_on_error: yes 

- name: Create Cluster Issuser
  kubernetes.core.k8s:
    state: present
    kubeconfig: /home/{{admin_account}}/.kube/config
    definition: "{{ lookup('template', 'templates/clusterissuer.j2') | from_yaml_all }}"
    validate:
      fail_on_error: yes 
