
- name: Install cert-manager Helm chart
  kubernetes.core.helm_repository:
    name: cert-manager                         # The name of the Helm release
    chart_ref: oci://harbor.test.local/library/cert-manager  # The OCI chart location
    chart_version: v1.14.4                     # The version of the chart to install
    release_namespace: cert-manager            # The namespace where the release will be created
    create_namespace: true                     # Automatically create the namespace if it doesn't exist
    values:                                    # Set Helm values directly
      installCRDs: true
    state: '{{ package_state }}'

# tasks/main.yml
#- name: Add the Jetstack Helm repository for cert-manager
#  kubernetes.core.helm_repository:
#    name: harbor
#    repo_url:  https://harbor.test.local/library/cert-manager 
#    validate_certs: false
#
#- name: Install Cert-Manager with Helm chart
#  kubernetes.core.helm:
#    name: cert-manager
#    chart_ref: jetstack/cert-manager
#    release_namespace: cert-manager
#    create_namespace: true
#    kubeconfig: /home/{{admin_account}}/.kube/config
#    values:
#      installCRDs: true
#    state: present
#
#- name: Create or update the TLS secret
#  kubernetes.core.k8s:
#    state: present
#    kubeconfig: /home/{{admin_account}}/.kube/config
#    definition: "{{ lookup('template', 'templates/tls.secret.j2') | from_yaml_all }}"
#
#- name: Create Cluster Issuser
#  kubernetes.core.k8s:
#    state: present
#    kubeconfig: /home/{{admin_account}}/.kube/config
#    definition: "{{ lookup('template', 'templates/clusterissuer.j2') | from_yaml_all }}"