- name: Install cert-manager Helm chart
  kubernetes.core.helm:
    release_name: cert-manager                # The name of the Helm release
    chart_ref: oci://harbor.test.local/library/cert-manager  # OCI chart reference
    chart_version: v1.14.4                     # Helm chart version
    namespace: cert-manager                   # Kubernetes namespace for the release
    create_namespace: true                    # Create the namespace if it doesn't exist
    values: "{{ lookup('template', 'values.j2') | from_yaml }}"
    state: "{{ package_state }}"
  register: helm_result

- name: Debug Helm install result
  debug:
    var: helm_result                           

- name: Create or update the TLS secret
  kubernetes.core.k8s:
    state: "{{ package_state }}"
    kubeconfig: /home/{{admin_account}}/.kube/config
    definition: "{{ lookup('template', 'templates/tls.secret.j2') | from_yaml_all }}"

- name: Create Cluster Issuser
  kubernetes.core.k8s:
    state: "{{ package_state }}"
    kubeconfig: /home/{{admin_account}}/.kube/config
    definition: "{{ lookup('template', 'templates/clusterissuer.j2') | from_yaml_all }}"