---

collections:

  # source

  ## https://github.com/ansible-collections/kubernetes.core/releases
  - name: community.kubernetes
    version: 2.3.2
  # source
  ## https://galaxy.ansible.com/awx/awx
  ## https://github.com/ansible/awx/releases
  - name: awx.awx
    version: 21.4.0
