---
# tasks file for manage_service_mesh_deployment

- name: Manage NGINX NIC Deployment
  kubernetes.core.k8s:
    state: "{{ package_state }}"
    definition: "{{ lookup('file', 'files/{{item}}.yaml') | from_yaml_all }}"  
  with_items: 
    - prometheus
    - grafana
    - otel-collector
    - jaeger



  

