apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-ingress
  # use annotations with k8s version < 1.18.0
  annotations:
    kubernetes.io/ingress.class: "nginx"
    appprotect.f5.com/app-protect-policy: "default/dataguard-alarm"
    appprotect.f5.com/app-protect-enable: "True"
    appprotect.f5.com/app-protect-security-log-enable: "True"
    appprotect.f5.com/app-protect-security-log: "default/logconf"
    appprotect.f5.com/app-protect-security-log-destination: "syslog:server=syslog-svc.default:514" 
spec:
  # ingressClassName: nginx # use only with k8s version >= 1.18.0
  tls:
  - hosts:
    - "cafe.{{local_domain}}"
    secretName: cafe-secret
  rules:
  - host: "cafe.{{local_domain}}"
    http:
      paths:
      - path: /tea
        pathType: Prefix
        backend:
          service:
            name: tea-svc
            port: 
              name: http
      - path: /coffee
        pathType: Prefix
        backend:
          service:
            name: coffee-svc
            port: 
              name: http
