apiVersion: "cis.f5.com/v1"
kind: IngressLink
metadata:
  name: vs-ingresslink-test
  namespace: nginx-ingress
spec:
  virtualServerAddress: "{{app_address}}"
  host: "cafe.{{local_domain}}"
  iRules:
    - /Common/Shared/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: ingresslink
