---
# Deploy Ingresslink with ExternalDNS
- name: Deploy Ingresslink with ExternalDNS
  hosts: master
  gather_facts: false

  vars_files:
    - ../vars/k8s_secret.yaml

  vars:
    vs_name: cafe.laptop.local

  tasks:
    - name: CIS Install 
      include_role:
        name: install_cis