---
# Deploy Ingresslink with ExternalDNS
- name: Deploy Ingresslink with ExternalDNS
  hosts: Local
  gather_facts: false

  vars:
    vs_name: cafe.laptop.local

  tasks:
    - name: BIG-IP credentials as Kubernetes Secrets
      ansible.builtin.command: 
        cmd: kubectl create secret generic bigip-login -n kube-system --from-literal=username=admin --from-literal=password="{{ bigip_passwd }}"

