---
- name: Playbook for Using a Variety of Tower Modules
  hosts: nodes
  gather_facts: false
  becomes: true

  tasks:

  - name: Ensure Pip is installed
    packages:
      name: python-pip
      state: present
