---
- name: Playbook for Using a Variety of Tower Modules
  hosts: nodes
  gather_facts: false

  tasks:

  - name: Get a list of all pods from any namespace
    kubernetes.core.k8s_info:
      kind: pods
    register: pods_list