---
- name: Playbook for Using a Variety of Tower Modules
  hosts: nodes
  gather_facts: false
  collections: 
    - community.kubernetes

  tasks:

  - name: Ensure Pip is installed
    packages:
      name: python-pip
      state: present

  - name: Get a list of all pods from any namespace
    community.kubernetes.k8s_info:
      kind: pods
    register: pods_list