---
- name: Playbook for Using a Variety of Tower Modules
  hosts: nodes
  gather_facts: false
  become: true

  tasks:

  - name: Ensure Pip is installed
    ansible.builtin.packages:
      name: python-pip
      state: present
