---
- name: Playbook for test secrets
  hosts: localhost
  connection: local
  gather_facts: false

- name: Use vault variables
  vars_files: k8s_secret.yaml 
  tasks:

  - name: Show vault variable value
    debug:
      var: bigip_password