---
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - /vars/k8s_secret.yaml

  tasks:
  - name: Echo the BIGIP password
    shell: echo $BIGIP_PASSWD
    environment: 
      $BIGIP_PASSWD: "{{bigip_passwd}}"
    register: echo_results

  - name: Show the echo_result
    debug: var=echo_result.stdout
