---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vars/k8s_secret.yaml

  tasks:
    - name: Echo the BIGIP password
      shell: echo $BIGIP_PASSWD
      environment: 
        BIGIP_PASSWD: "{{ bigip_passwd }}"
      register: echo_result

    - name: Show the echo result
      debug: var=echo_result.stdout
