    - name: Push Helm charts to Harbor
      ansible.builtin.shell: |
        helm push {{ item.destination }}/{{item.untar_dir}}.{{item.version}}.tgz oci://{{ registry_url }}
      loop: "{{ charts }}"
