---
# Remove NSM 
- name: Install Cafe App
  hosts: master
  gather_facts: false

  vars:
    package_state: present

  tasks:

    - name: NSM Deploy
      import_role:
        name: manage_service_mesh_deployment
