---
# Deploy Ingresslink with ExternalDNS
- name: Deploy Ingresslink with ExternalDNS
  hosts: master
  gather_facts: false

  vars_files:
    - ../vars/k8s_secret.yaml

  vars:
    vs_name: cafe.laptop.local
    package_state: absent
    secret_state: delete

  tasks:
    - name: Ensure Kubernetes is installed
      pip:
        name: 
          - Kubernetes>=12.0.0
          - PyYAML
          - kubernetes-validate
        state: present
      become: true 

    - name: CIS  
      import_role:
        name: install_cis
    - name: NGINX IC
      import_role:
        name: install_nic

    - name: Cafe APP
      import_role:
        name: deploy_cafe

    - name: Ingresslink and ExternalDNS
      import_role:
        name: manage-ingresslink-dns