---
# Deploy Ingresslink with ExternalDNS
- name: Deploy Ingresslink with ExternalDNS
  hosts: master
  gather_facts: false

  vars_files:
    - ../vars/k8s_secret.yaml

  vars:
    vs_name: cafe.laptop.local
    package_state: absent
    secret_state: delete

  tasks:
    - name: Delete a nginx-ingress namespace
      kubernetes.core.k8s:
        name: nginx-ingress
        kind: Namespace
        state: "{{package_state}}"

    - name: BIG-IP credentials as Kubernetes Secrets
      ansible.builtin.command: 
        cmd: kubectl delete secret generic bigip-login -n kube-system 
      ignore_errors: true

    - name: CIS  
      import_role:
        name: install_cis

    - name: NGINX IC
      import_role:
        name: install_nic

    - name: Cafe APP
      import_role:
        name: deploy_cafe

    - name: Ingresslink and ExternalDNS
      import_role:
        name: manage-ingresslink-dns