---
# Cafe App
- name: Install Cafe App
  hosts: master
  gather_facts: false

  vars_files:
    - ../vars/k8s_secret.yaml

  vars:
    local_domain: 1laptop.local
    package_state: present
    secret_state: create

  tasks:

    - name: Cafe APP
      import_role:
        name: manage_app2_deployment
