---
# Deploy NSM
- name: Install NGINX Service Mesh
  hosts: master
  gather_facts: false

  vars:
    package_state: present
    
  tasks:

    - name: Move Mesh Files
      ansible.builtin.copy:
        src: nginx-meshctl_linux
        dest: /usr/local/bin/nginx-meshctl
        mode: '0755'
        force: yes
      become: yes

    - name: NSM Deploy
      import_role:
        name: manage_service_mesh_deployment
    
    - name: Install NGINX Service Mesh
      ansible.builtin.command: nginx-meshctl deploy --prometheus-address "prometheus.nsm-monitoring.svc:9090" --telemetry-exporters "type=otlp,host=otel-collector.nsm-monitoring.svc,port=4317" --telemetry-sampler-ratio 1 --disabled-namespaces "nsm-monitoring"
      become: yes

