---
# Cafe App
- name: Install Cafe App
  hosts: master
  gather_facts: false

  vars_files:
    - ../vars/k8s_secret.yaml
    - ../vars/cafe-app.crt
    - ../vars/cafe-app.ket

  vars:
    vs_name: cafe.laptop.local
    package_state: present
    secret_state: create

  tasks:
    - name: Cafe Secret
      ansible.builtin.command: 
        cmd: kubectl create secret tls cafe-secret --cert="{{cafe-app.crt}}" --key="{{cafe-app.key}}"
      ignore_errors: true
      no_log: true 
              
    - name: Cafe APP
      import_role:
        name: manage_app_deployment
