---
# Deploy NSM
- name: Install NGINX Service Mesh
  hosts: master
  gather_facts: false

  vars:
      package_state: present
      secret_state: create

  tasks:
    - name: Ensure Pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present
      become: true

    - name: Ensure Kubernetes is installed
      pip:
        name: 
          - Kubernetes>=12.0.0
          - PyYAML
          - kubernetes-validate
        state: present
      become: true 
    - name: Move Mesh Files
      ansible.builtin.copy:
        src: nginx-meshctl_linux
        dest: /usr/local/bin/nginx-meshctl
        mode: '0755'
        force: yes
      become: yes

    - name: NSM Packages
      import_role:
        name: manage_service_mesh_deployment
    
    - name: Install NGINX Service Mesh
      ansible.builtin.shell: nginx-meshctl deploy --mtls-mode off --prometheus-address "prometheus.nsm-monitoring.svc:9090" --telemetry-exporters "type=otlp,host=otel-collector.nsm-monitoring.svc,port=4317" --telemetry-sampler-ratio 1 --disabled-namespaces "nsm-monitoring"

      

