---
# Cafe App
- name: Install Cafe App
  hosts: master
  gather_facts: false

  vars_files:
    - ../vars/k8s_secret.yaml

  vars:
    vs_name: cafe.laptop.local
    package_state: present
    secret_state: create

  tasks:
#    - name: Cafe Secret
#      ansible.builtin.command: 
#        cmd: kubectl create secret tls cafe-secret --cert="{{app-cert}}" --key="{{app-key}}"
#      ignore_errors: true
#      no_log: true 
              
    - name: Cafe APP
      import_role:
        name: manage_app_deployment
