---
- hosts: localhost
  gather_facts: false
  become: true
  
  vars_files:
    - vars/docker_login.yaml
    - vars/docker_images.yaml

  tasks:
    - name: Login to Repo
      import_role:
        name: docker_login

    - name: Push Docker Images
      import_role:
        name: docker_push

  

