---
- hosts: master
  gather_facts: false
  become: true
  
  vars_files:
    - vars/repo.yaml
  
  vars:
    package_state: absent

  tasks:

    - name: Pull nginx-ingress chart from Harbor OCI registry
      kubernetes.core.helm:
        name: nginx-ingress
        #chart_ref: oci://harbor.test.local/library/nginx-ingress
        release_namespace: ingress-nginx
        create_namespace: true
        force: true
        kubeconfig: /home/ubuntu/.kube/config
        values:
          controller:
            replicaCount: 2
            service:
              type: LoadBalancer