---
- hosts: master
  gather_facts: false
  become: true
  
  vars_files:
    - vars/repo.yaml
  
  vars:
    package_state: present

  tasks:
    - name: Install Python Kubernetes 
      import_role:
        name: python_k8s

    - name: Deploy Helm Charts
      import_role:
        name: deploy_charts