---
- hosts: master
  gather_facts: false
  become: true
  
  vars_files:
    - vars/nginx_chart_vars.yaml
  
  vars:
    package_state: present


  tasks:

    - name: Deploy Helm Charts
      import_role:
        name: deploy_charts