---
- hosts: master
  gather_facts: false
  become: true
  
  vars_files:
    - vars/repo.yaml
  
  vars:
    package_state: absent

  tasks:

    - name: Deploy Helm Charts
      import_role:
        name: deploy_charts