---
- hosts: localhost
  gather_facts: false
  become: true
  
  vars_files:
    - vars/nginx_login.yaml
    - vars/nginx_images.yaml
    - vars/extras.yaml
  
  vars:
    registry_host: "private-registry.nginx.com"
    image_repo: "nginx-ic-nap/nginx-plus-ingress"
    image_tag: "3.2.1"
    jwt_token: "{{ nginx_jwt }}"  # Or use vars/vault
    full_image: "{{ registry_host }}/{{ image_repo }}:{{ image_tag }}"

  tasks:
    - name: Log in to private registry using JWT
      community.docker.docker_login:
        registry_url: "https://{{ registry_host }}"
        username: "{{jwt_token }}"  # standard for bearer token logins
        password: "{{ jwt_token }}"
        reauthorize: yes

    - name: Pull the image from the private registry
      community.docker.docker_image:
        name: "{{ full_image }}"
        source: pull

    - name: Show pulled image details
      ansible.builtin.debug:
        msg: "Successfully pulled {{ full_image }}"

