---
- hosts: localhost
  gather_facts: false
  become: true
  
  vars:

  vars_files:
    - vars/nginx_login.yaml
    - vars/nginx_images.yaml
    - vars/extras.yaml

  tasks:
    - name: Login to Repo
      import_role:
        name: docker_login

    - name: Pull Docker Images
      import_role:
        name: docker_pull

