---
# tasks file for manage-ingresslink-dns
- name: Manage Ingresslink and ExternalDNS CRD
  kubernetes.core.k8s:
    state: "{{ package_state }}"
    definition: "{{ lookup('file', 'files/{{item}}.yaml') | from_yaml_all }}"  
  with_items: 
    - vs-ingresslink
    - edns-cafe