---
# tasks file for roles/install_nic
- name: Manage NGINX NIC Deployment
  kubernetes.core.k8s:
    state: "{{ package_state }}"
    definition: "{{ lookup('file', 'files/{{item}}.yaml') | from_yaml_all }}"  
  with_items: 
    - k8s.nginx.org_virtualservers
    - k8s.nginx.org_virtualserverroutes
    - k8s.nginx.org_transportservers
    - k8s.nginx.org_policies
    - ns-and-sa
    - rbac
    - default-server-secret
    - nginx-config
    - ingress-class
    - nginx-ingress
    - nginx-service