---
# tasks file for roles/install_cis
- name: BIG-IP credentials as Kubernetes Secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: bigip-login
        namespace: kube-system
      stringData:
        username: admin
        password: '{{ bigip_passwd }}'
      type: Opaque"

- name: Apply Service Account, Cluster Role and Cluster Role Binding
  kubernetes.core.k8s:
    state: '{{ package_state }}'
    definition: "{{ lookup('file', 'files/bigip-ctlr-clusterrole.yaml') | from_yaml_all }}"
    validate:
      fail_on_error: yes

- name: Apply CRD Schea
  kubernetes.core.k8s:
    state: '{{ package_state }}'
    definition: "{{ lookup('file', 'files/customresourcedefinitions.yaml') | from_yaml_all }}"
    validate:
      fail_on_error: yes

- name: Apply BIGIP CTRL Manifest
  kubernetes.core.k8s:
    state: '{{ package_state }}'
    definition: "{{ lookup('template', 'templates/{{deployment_type}}_deployment.yaml') | from_yaml_all }}"
    validate:
      fail_on_error: yes
