---
# tasks file for roles/nginx_common_resources
- name: Modify NGINX IC custom resource definitions for VirtualServer and VirtualServerRoute, TransportServer and Policy resources
  kubernetes.core.k8s:
    state: "{{ package_state }}"
    definition: "{{ lookup('file', 'files/{{item}}.yaml') | from_yaml_all }}"  
  with_items: 
    - k8s.nginx.org_virtualservers
    - k8s.nginx.org_virtualserverroutes
    - k8s.nginx.org_transportservers
    - k8s.nginx.org_policies