admin_account: ubuntu

tls_crt: |
  -----BEGIN CERTIFICATE-----
  MIIEQjCCAqqgAwIBAgIBDTANBgkqhkiG9w0BAQsFADA1MRMwEQYDVQQKDApURVNU
  LkxPQ0FMMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjUwMTIw
  MDUwMTUwWhcNNDQxMjI2MDMwMTMwWjBsMQswCQYDVQQGEwJVUzERMA8GA1UECAwI
  VmlyZ2luaWExFDASBgNVBAcMC1NwcmluZ2ZpZWxkMQ0wCwYDVQQKDARUZXN0MQww
  CgYDVQQLDANMYWIxFzAVBgNVBAMMDmxhYi50ZXN0LmxvY2FsMIIBIjANBgkqhkiG
  9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxZNqwrdTjRaBS0g+lV3LC8I1Hs+VkcXUpK+k
  aPswoaK77lv6pzOQ2H099GtGuXnp8momfO/GVEYZdPDEnVCDEPhaX+uXMsVuJJPD
  TvbA7ml/7yigWK398pEglO3sErK0jBpIXeOc3OYlXLb+GD511NELIu05jPkp6cbP
  ZPugnyUkGFBqY46rp0mFEa+aLWsWLmVhfkgitmG8eGzTcpdr1NEF7b8CuPyn8jha
  epGYpqbg9tSN5vMDeTdYsaEnoMCxABn0WZO1MACy5tAvZiVg8kKQY8MNdJNxGGsA
  WVS+9hYPpGKVe7YpbkDDvLl3nljpUMWvwlT+Bgyqy+j6vWU38wIDAQABo4GlMIGi
  MB8GA1UdIwQYMBaAFGsuTIrFX96PIa1W0Dodm13Q1K3DMBIGA1UdEwEB/wQIMAYB
  Af8CAQAwDgYDVR0PAQH/BAQDAgHGMB0GA1UdDgQWBBQQ0ZMyK6JN1mEDwSd7x+iw
  7q69VTA8BggrBgEFBQcBAQQwMC4wLAYIKwYBBQUHMAGGIGh0dHA6Ly9pcGEtY2Eu
  dGVzdC5sb2NhbC9jYS9vY3NwMA0GCSqGSIb3DQEBCwUAA4IBgQA48wPXR/5hcOZV
  KIlsOIwsdiWb4FwuxSSQiZkfYkzskjKnww1kwYSTJZqhurONE1UV2ufVafxsSR5u
  g3xcpNClm1QCqqXrM6o6NuHWHgq/vhVUy6Hy/tD4vZXxGjeE6k/2ZQXezNbM3G9n
  xYHPMV5cNLypKvBNUSjcuPuv1WAKOIL2vrXk4QnF405Ciy7l0d0YVjDwQHo49+WS
  ++HfoWUFZpW3o+ErhV4pmkpKmDNTKhJDO2Gl1GR/n8KEPK59J/ojvZ9lws+rld9y
  8Gae90Bx6sIi+auyt4jlGAkK5EKCiJhFni9CyG66ig0+b6TH92m4FjlldhvGO+rl
  tmDylcage5QHtBagY2a4krGzGMlXPvB9CWmq8lYk6Vu/CqVfxgvO/WXTGuK/bP5/
  7YrBlEed5mK8fbN041U6+Fnrj6iOa4l0Lt8myJis5kgCWnqJf1waUJ3By7FOS13U
  8MJKiztVJ6xirKy6uz6r+pjG3M2++7bAdgKBXIeT5zztVuyCyAw=
  -----END CERTIFICATE-----

tls_key: | 
  -----BEGIN PRIVATE KEY-----
  MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDFk2rCt1ONFoFL
  SD6VXcsLwjUez5WRxdSkr6Ro+zChorvuW/qnM5DYfT30a0a5eenyaiZ878ZURhl0
  8MSdUIMQ+Fpf65cyxW4kk8NO9sDuaX/vKKBYrf3ykSCU7ewSsrSMGkhd45zc5iVc
  tv4YPnXU0Qsi7TmM+Snpxs9k+6CfJSQYUGpjjqunSYURr5otaxYuZWF+SCK2Ybx4
  bNNyl2vU0QXtvwK4/KfyOFp6kZimpuD21I3m8wN5N1ixoSegwLEAGfRZk7UwALLm
  0C9mJWDyQpBjww10k3EYawBZVL72Fg+kYpV7tiluQMO8uXeeWOlQxa/CVP4GDKrL
  6Pq9ZTfzAgMBAAECggEAAkc5MPU8VPpkyfED/JNbwDP9gqLV5eWQ76jYCcH7QWTK
  7VzglBD9i/q6k33IdGKyWHJHU9IVjld1MaDqriT5w74WeNBvyXe5F6ebzjQEvpgf
  /H/A8VZJ+VlnDtZkGdDpthzVSl1wvx/wvMZYYNF93SCZxmUGABMsxm3dehvUrkEW
  AcglNoKR2E7xzf4YrpvP5wGo+NNI7Qb+CTyM7nf7wrsAAs3blX6YkvtC/Ds9r9GR
  Bxkk9sXEYNKjhtxtOiNAViNuCKnizcfEI7BgO1FGp7i9kOZ2zceFpRB16NcHlsWW
  m1SmcVhiYoWH1Y5rS3sUpHQE5uYav6h5AtNz/scq4QKBgQDuEJ2RBQH6MlWZ9hyl
  Ie1J4sceTeoDYuvAWfC9M1ifwJWCspLUBgUyufw9dpkvALvVzoZll76fLnMqLGWx
  pDbWING2t6Mw5tDdOVW7iTaufTJDKiHLddo73zwsFRiqzQxxHUpHHjcUkIpn/ndj
  9j1WBF+mFBLWXtf8jjldEVQe+QKBgQDUdesoK7ohi64TMfH4ujoUBR6bx5fwiHAU
  zUVgbdP1bs21X1S5AmwCWT4YdxJ5Pd/Alv2iediZKiWwE2Ixgmw7gz04CXvLSszs
  Ynf0Q7u1IypPLI/i3/sfWBZa25lUHqkmUNuMvVzN3wjQLOVBbvdWcD9PIj7i/v4r
  kssteXmNSwKBgA/oJk8ZUY+BK30VF8bk5HEKaRmaRSeixXPdzpslwicyfAr2mZ73
  JAPGr5b/xK6CUwqvOQWyxPbn6KQJwWXEPjHCkaCu1oWe9pfBi/vy6CdykBgyyX1J
  y6IygVfEtRg8iTdJqLvlxfJm0giu1RVlz6Vet3FmZ/fQ8IecjTKtxLwpAoGAVqrb
  iIF95h1Cn1XqbRoagvwrpkRfOKGPhwzNVi63HhFbHLeMqgPQ54xcBkLcaFTTJ47w
  XAz0TFajFRZzIdsgJ467tFY6B4211l+8qwnOUm/L3IxDDbtshza5t8qI24W+XoDx
  bpH4f4qR38nQo0aO4tXbHX7MxHBcYo35D83Txc0CgYAEuTF0lghI331tsIizDNAZ
  LdTjAJgA2MhxnpA6tA8eAlEx/yBgrz+FVKt/Eq+kOEYrdiAuuC1hjZfzTVuh9DyT
  ghmizd/4gSIBElBZ/StdhNOkhE6YAm7m+EnrUPsDgu2UbSI9Hx/baLlxPJ5c2AMk
  jzlQIfD/bIhYv5HgLWR2JA==
  -----END PRIVATE KEY-----
